# Generated by Django 5.2 on 2025-04-22 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='tên danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='mô tả')),
            ],
            options={
                'verbose_name': 'danh mục sự kiện',
                'verbose_name_plural': 'danh mục sự kiện',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tiêu đề')),
                ('description', models.TextField(verbose_name='mô tả')),
                ('start_date', models.DateField(verbose_name='ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='ngày kết thúc')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='giờ bắt đầu')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='giờ kết thúc')),
                ('location', models.CharField(max_length=200, verbose_name='địa điểm')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã xuất bản'), ('cancelled', 'Đã hủy'), ('completed', 'Đã hoàn thành')], default='draft', max_length=20, verbose_name='trạng thái')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='số người tham gia tối đa')),
                ('registration_required', models.BooleanField(default=False, verbose_name='yêu cầu đăng ký')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='hạn đăng ký')),
                ('parent_approval_required', models.BooleanField(default=False, verbose_name='yêu cầu phụ huynh phê duyệt')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='hình ảnh')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='event_attachments/', verbose_name='tệp đính kèm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cập nhật lần cuối')),
                ('classrooms', models.ManyToManyField(blank=True, related_name='events', to='classes.classroom', verbose_name='lớp tham gia')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='người tạo')),
                ('organizers', models.ManyToManyField(blank=True, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='người tổ chức')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory', verbose_name='danh mục')),
            ],
            options={
                'verbose_name': 'sự kiện',
                'verbose_name_plural': 'sự kiện',
                'ordering': ['-start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='ngày đăng ký')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy'), ('attended', 'Đã tham gia')], default='pending', max_length=20, verbose_name='trạng thái')),
                ('parent_approval', models.BooleanField(blank=True, default=False, null=True, verbose_name='phụ huynh đã duyệt')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='thời gian duyệt')),
                ('attended', models.BooleanField(default=False, verbose_name='đã tham gia')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='ghi chú')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_participants', to=settings.AUTH_USER_MODEL, verbose_name='người duyệt')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event', verbose_name='sự kiện')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='người tham gia')),
            ],
            options={
                'verbose_name': 'người tham gia sự kiện',
                'verbose_name_plural': 'người tham gia sự kiện',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
