# Generated by Django 5.2 on 2025-04-22 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='nghề nghiệp')),
                ('workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='nơi làm việc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'phụ huynh',
                'verbose_name_plural': 'phụ huynh',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='mã học sinh')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, verbose_name='giới tính')),
                ('admission_date', models.DateField(verbose_name='ngày nhập học')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Không rõ')], default='Unknown', max_length=10, verbose_name='nhóm máu')),
                ('health_status', models.TextField(blank=True, null=True, verbose_name='tình trạng sức khỏe')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='dị ứng')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ghi chú')),
                ('parents', models.ManyToManyField(related_name='children', to='students.parent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'học sinh',
                'verbose_name_plural': 'học sinh',
            },
        ),
    ]
