# Generated by Django 5.2 on 2025-04-22 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parents',
        ),
        migrations.AddField(
            model_name='student',
            name='current_grade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='lớp hiện tại'),
        ),
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='chiều cao (cm)'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='trường học trước đây'),
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='cân nặng (kg)'),
        ),
        migrations.CreateModel(
            name='ParentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('father', 'Cha'), ('mother', 'Mẹ'), ('guardian', 'Người giám hộ'), ('other', 'Khác')], max_length=50, verbose_name='quan hệ')),
                ('is_primary', models.BooleanField(default=False, verbose_name='là người giám hộ chính')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ghi chú')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to='parents.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='students.student')),
            ],
            options={
                'verbose_name': 'quan hệ phụ huynh-học sinh',
                'verbose_name_plural': 'quan hệ phụ huynh-học sinh',
                'unique_together': {('parent', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
