# Generated by Django 5.2 on 2025-04-22 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='tên năm học')),
                ('start_date', models.DateField(verbose_name='ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='ngày kết thúc')),
                ('is_current', models.BooleanField(default=False, verbose_name='là năm học hiện tại')),
            ],
            options={
                'verbose_name': 'năm học',
                'verbose_name_plural': 'năm học',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='tên khối')),
                ('description', models.TextField(blank=True, null=True, verbose_name='mô tả')),
            ],
            options={
                'verbose_name': 'khối lớp',
                'verbose_name_plural': 'khối lớp',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='tên lớp')),
                ('room_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='số phòng')),
                ('max_students', models.PositiveIntegerField(default=35, verbose_name='số học sinh tối đa')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.academicyear', verbose_name='năm học')),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='teachers.teacher', verbose_name='giáo viên chủ nhiệm')),
            ],
            options={
                'verbose_name': 'lớp học',
                'verbose_name_plural': 'lớp học',
            },
        ),
        migrations.CreateModel(
            name='ClassroomStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='ngày vào lớp')),
                ('roll_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='số thứ tự')),
                ('status', models.CharField(choices=[('active', 'Đang học'), ('transferred', 'Đã chuyển'), ('graduated', 'Đã tốt nghiệp'), ('suspended', 'Tạm nghỉ')], default='active', max_length=20, verbose_name='trạng thái')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classroom', verbose_name='lớp học')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='học sinh')),
            ],
            options={
                'verbose_name': 'học sinh trong lớp',
                'verbose_name_plural': 'học sinh trong lớp',
                'unique_together': {('student', 'classroom')},
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='classes', through='classes.ClassroomStudent', to='students.student', verbose_name='học sinh'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.grade', verbose_name='khối lớp'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='tên môn học')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='mã môn học')),
                ('description', models.TextField(blank=True, null=True, verbose_name='mô tả')),
                ('grades', models.ManyToManyField(related_name='subjects', to='classes.grade', verbose_name='khối lớp')),
            ],
            options={
                'verbose_name': 'môn học',
                'verbose_name_plural': 'môn học',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Thứ hai'), (1, 'Thứ ba'), (2, 'Thứ tư'), (3, 'Thứ năm'), (4, 'Thứ sáu'), (5, 'Thứ bảy'), (6, 'Chủ nhật')], verbose_name='ngày trong tuần')),
                ('start_time', models.TimeField(verbose_name='thời gian bắt đầu')),
                ('end_time', models.TimeField(verbose_name='thời gian kết thúc')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='classes.classroom', verbose_name='lớp học')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='classes.subject', verbose_name='môn học')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='teachers.teacher', verbose_name='giáo viên')),
            ],
            options={
                'verbose_name': 'thời khóa biểu',
                'verbose_name_plural': 'thời khóa biểu',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'academic_year')},
        ),
        migrations.CreateModel(
            name='TeacherSubjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='classes.classroom', verbose_name='lớp học')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='classes.subject', verbose_name='môn học')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='teachers.teacher', verbose_name='giáo viên')),
            ],
            options={
                'verbose_name': 'phân công giảng dạy',
                'verbose_name_plural': 'phân công giảng dạy',
                'unique_together': {('teacher', 'subject', 'classroom')},
            },
        ),
    ]
