apiVersion: v1
kind: Secret
metadata:
  name: school-management-secret
  annotations:
    kubernetes.io/created-by: "manual"
    environment: "production"
    note: "Secret cho môi trường sản xuất (PROD)"
type: Opaque
stringData:
  SECRET_KEY: "${PROD_SECRET_KEY}"
  DB_USER: "${PROD_DB_USER}"
  DB_PASSWORD: "${PROD_DB_PASSWORD}"
  EMAIL_HOST_PASSWORD: "${PROD_EMAIL_PASSWORD}"
