# Generated by Django 5.2 on 2025-04-22 10:19

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_student_info', 'Xem thông tin học sinh'), ('edit_student_info', 'Chỉnh sửa thông tin học sinh'), ('view_grades', 'Xem điểm số'), ('edit_grades', 'Chỉnh sửa điểm số'), ('view_attendance', 'Xem điểm danh'), ('edit_attendance', 'Chỉnh sửa điểm danh'), ('view_timetable', 'Xem thời khóa biểu'), ('edit_timetable', 'Chỉnh sửa thời khóa biểu')], 'verbose_name': 'người dùng', 'verbose_name_plural': 'người dùng'},
        ),
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, help_text='Quyền hạn cụ thể cho người dùng này ngoài các quyền mặc định.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='quyền hạn tùy chỉnh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[accounts.models.User.validate_birth_date], verbose_name='ngày sinh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='địa chỉ email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải đúng định dạng Việt Nam. Ví dụ: +84 912 345 678 hoặc 0912345678', regex='^(0|\\+84)(\\s|\\.)?((3[2-9])|(5[2689])|(7[06-9])|(8[1-689])|(9[0-9]))(\\d)(\\s|\\.)?(\\d{3})(\\s|\\.)?(\\d{3})$')], verbose_name='số điện thoại'),
        ),
    ]
