# Generated by Django 5.2 on 2025-04-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_custom_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_student_info', 'Xem thông tin học sinh'), ('edit_student_info', 'Chỉnh sửa thông tin học sinh'), ('view_grades', 'Xem điểm số'), ('edit_grades', 'Chỉnh sửa điểm số'), ('view_attendance', 'Xem điểm danh'), ('edit_attendance', 'Chỉnh sửa điểm danh'), ('view_timetable', 'Xem thời khóa biểu'), ('edit_timetable', 'Chỉnh sửa thời khóa biểu'), ('access_admin_site', 'Truy cập trang quản trị Django')], 'verbose_name': 'người dùng', 'verbose_name_plural': 'người dùng'},
        ),
    ]
