# Generated by Django 5.2 on 2025-04-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('reset_user_password', 'Đặt lại mật khẩu người dùng'), ('activate_user', 'Kích hoạt tài khoản người dùng'), ('deactivate_user', 'Vô hiệu hóa tài khoản người dùng'), ('view_student_info', 'Xem thông tin học sinh'), ('edit_student_info', 'Chỉnh sửa thông tin học sinh'), ('view_grades', 'Xem điểm số'), ('edit_grades', 'Chỉnh sửa điểm số'), ('view_attendance', 'Xem điểm danh'), ('edit_attendance', 'Chỉnh sửa điểm danh'), ('view_timetable', 'Xem thời khóa biểu'), ('edit_timetable', 'Chỉnh sửa thời khóa biểu'), ('access_admin_site', 'Truy cập trang quản trị Django')], 'verbose_name': 'người dùng', 'verbose_name_plural': 'người dùng'},
        ),
    ]
