# Generated by Django 5.2 on 2025-04-22 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='mã giáo viên')),
                ('date_of_joining', models.DateField(verbose_name='ngày vào làm')),
                ('qualification', models.CharField(choices=[('bachelor', 'Cử nhân'), ('master', 'Thạc sĩ'), ('phd', 'Tiến sĩ'), ('other', 'Khác')], default='bachelor', max_length=20, verbose_name='bằng cấp')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='kinh nghiệm (năm)')),
                ('specialization', models.CharField(max_length=100, verbose_name='chuyên môn')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='tên người liên hệ khẩn cấp')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='số điện thoại khẩn cấp')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ghi chú')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'giáo viên',
                'verbose_name_plural': 'giáo viên',
            },
        ),
    ]
