# Generated by Django 5.2 on 2025-04-22 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='nghề nghiệp')),
                ('workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='nơi làm việc')),
                ('education', models.CharField(blank=True, max_length=100, null=True, verbose_name='trình độ học vấn')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='người liên hệ khẩn cấp')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='số điện thoại khẩn cấp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'phụ huynh',
                'verbose_name_plural': 'phụ huynh',
            },
        ),
    ]
