# Generated by Django 5.2 on 2025-04-22 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tiêu đề')),
                ('description', models.TextField(blank=True, null=True, verbose_name='mô tả')),
                ('file', models.FileField(upload_to='documents/', verbose_name='tệp tin')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='hình thu nhỏ')),
                ('document_type', models.CharField(choices=[('textbook', 'Sách giáo khoa'), ('worksheet', 'Bài tập'), ('exam', 'Đề kiểm tra'), ('lesson', 'Giáo án'), ('presentation', 'Bài thuyết trình'), ('reference', 'Tài liệu tham khảo'), ('other', 'Khác')], max_length=20, verbose_name='loại tài liệu')),
                ('access_level', models.CharField(choices=[('public', 'Công khai'), ('teachers', 'Chỉ giáo viên'), ('class', 'Chỉ lớp cụ thể'), ('private', 'Riêng tư')], default='public', max_length=20, verbose_name='mức độ truy cập')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cập nhật lần cuối')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='lượt xem')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='lượt tải')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='classes.classroom', verbose_name='lớp học')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='classes.subject', verbose_name='môn học')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='người tải lên')),
            ],
            options={
                'verbose_name': 'tài liệu',
                'verbose_name_plural': 'tài liệu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='thời gian truy cập')),
                ('is_download', models.BooleanField(default=False, verbose_name='là lượt tải về')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document', verbose_name='tài liệu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='người dùng')),
            ],
            options={
                'verbose_name': 'lượt truy cập tài liệu',
                'verbose_name_plural': 'lượt truy cập tài liệu',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='tên danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='mô tả')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentcategory', verbose_name='danh mục cha')),
            ],
            options={
                'verbose_name': 'danh mục tài liệu',
                'verbose_name_plural': 'danh mục tài liệu',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory', verbose_name='danh mục'),
        ),
    ]
