# Generated by Django 5.2 on 2025-04-22 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tiêu đề')),
                ('content', models.TextField(verbose_name='nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cập nhật lần cuối')),
                ('audience', models.CharField(choices=[('all', 'Toàn trường'), ('teachers', 'Giáo viên'), ('parents', 'Phụ huynh'), ('students', 'Học sinh'), ('class', 'Lớp cụ thể')], default='all', max_length=20, verbose_name='đối tượng')),
                ('is_important', models.BooleanField(default=False, verbose_name='quan trọng')),
                ('publish_date', models.DateTimeField(verbose_name='ngày xuất bản')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='ngày hết hạn')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/', verbose_name='tệp đính kèm')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classes.classroom', verbose_name='lớp')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='người tạo')),
            ],
            options={
                'verbose_name': 'thông báo',
                'verbose_name_plural': 'thông báo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tiêu đề')),
                ('content', models.TextField(verbose_name='nội dung')),
                ('category', models.CharField(choices=[('academic', 'Học tập'), ('behavior', 'Hạnh kiểm'), ('facility', 'Cơ sở vật chất'), ('teacher', 'Giáo viên'), ('suggestion', 'Đề xuất'), ('other', 'Khác')], max_length=20, verbose_name='danh mục')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời gian tạo')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('processing', 'Đang xử lý'), ('resolved', 'Đã giải quyết'), ('closed', 'Đã đóng')], default='pending', max_length=20, verbose_name='trạng thái')),
                ('response', models.TextField(blank=True, null=True, verbose_name='phản hồi')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='thời gian phản hồi')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedbacks/', verbose_name='tệp đính kèm')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='người được giao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='người gửi')),
            ],
            options={
                'verbose_name': 'phản hồi',
                'verbose_name_plural': 'phản hồi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='chủ đề')),
                ('content', models.TextField(verbose_name='nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời gian gửi')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='thời gian đọc')),
                ('is_read', models.BooleanField(default=False, verbose_name='đã đọc')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='messages/', verbose_name='tệp đính kèm')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='người nhận')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='người gửi')),
            ],
            options={
                'verbose_name': 'tin nhắn',
                'verbose_name_plural': 'tin nhắn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tiêu đề')),
                ('content', models.TextField(verbose_name='nội dung')),
                ('notification_type', models.CharField(choices=[('announcement', 'Thông báo chung'), ('message', 'Tin nhắn mới'), ('grade', 'Điểm mới'), ('attendance', 'Điểm danh'), ('event', 'Sự kiện'), ('leave', 'Yêu cầu nghỉ phép'), ('other', 'Khác')], max_length=20, verbose_name='loại thông báo')),
                ('content_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='loại nội dung')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID đối tượng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời gian tạo')),
                ('is_read', models.BooleanField(default=False, verbose_name='đã đọc')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='thời gian đọc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='người dùng')),
            ],
            options={
                'verbose_name': 'thông báo',
                'verbose_name_plural': 'thông báo',
                'ordering': ['-created_at'],
            },
        ),
    ]
