# Generated by Django 5.2 on 2025-04-22 07:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='tên loại kiểm tra')),
                ('description', models.TextField(blank=True, null=True, verbose_name='mô tả')),
                ('weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='trọng số')),
            ],
            options={
                'verbose_name': 'loại kiểm tra',
                'verbose_name_plural': 'loại kiểm tra',
            },
        ),
        migrations.CreateModel(
            name='AcademicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1', 'Học kỳ 1'), ('2', 'Học kỳ 2'), ('final', 'Cả năm')], max_length=10, verbose_name='học kỳ')),
                ('average_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='điểm trung bình')),
                ('rank', models.CharField(blank=True, max_length=20, null=True, verbose_name='xếp loại')),
                ('teacher_comments', models.TextField(blank=True, null=True, verbose_name='nhận xét của giáo viên')),
                ('parent_comments', models.TextField(blank=True, null=True, verbose_name='nhận xét của phụ huynh')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='ngày tạo')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_reports', to='classes.classroom', verbose_name='lớp học')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_reports', to='students.student', verbose_name='học sinh')),
            ],
            options={
                'verbose_name': 'báo cáo học tập',
                'verbose_name_plural': 'báo cáo học tập',
                'unique_together': {('student', 'classroom', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tiêu đề')),
                ('exam_date', models.DateField(verbose_name='ngày kiểm tra')),
                ('max_score', models.FloatField(default=10.0, verbose_name='điểm tối đa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='mô tả')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='classes.classroom', verbose_name='lớp học')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='classes.subject', verbose_name='môn học')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='teachers.teacher', verbose_name='giáo viên')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='grading.examtype', verbose_name='loại kiểm tra')),
            ],
            options={
                'verbose_name': 'bài kiểm tra',
                'verbose_name_plural': 'bài kiểm tra',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='điểm số')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='nhận xét')),
                ('date_graded', models.DateTimeField(auto_now_add=True, verbose_name='ngày chấm điểm')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='cập nhật lần cuối')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grading.exam', verbose_name='bài kiểm tra')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='học sinh')),
            ],
            options={
                'verbose_name': 'điểm số',
                'verbose_name_plural': 'điểm số',
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='SubjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='điểm trung bình')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='nhận xét')),
                ('academic_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_reports', to='grading.academicreport', verbose_name='báo cáo học tập')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_reports', to='classes.subject', verbose_name='môn học')),
            ],
            options={
                'verbose_name': 'báo cáo môn học',
                'verbose_name_plural': 'báo cáo môn học',
                'unique_together': {('academic_report', 'subject')},
            },
        ),
    ]
