apiVersion: v1
kind: Secret
metadata:
  name: school-management-secret
  annotations:
    kubernetes.io/created-by: "manual"
    environment: "development"
    note: "Secret cho môi trường phát triển (DEV)"
type: Opaque
stringData:
  # Các giá trị này sẽ được ghi đè bởi các secret cụ thể cho từng môi trường
  SECRET_KEY: "${SECRET_KEY}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
