apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
  - ../../base

patchesStrategicMerge:
  - patches/configmap.yaml
  - patches/django-deployment.yaml
  - patches/secret.yaml

images:
  - name: school-management
    newName: school-management
    newTag: latest
