# Generated by Django 5.2 on 2025-04-22 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='ngày')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cập nhật lần cuối')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='classes.classroom', verbose_name='lớp học')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='teachers.teacher', verbose_name='giáo viên điểm danh')),
            ],
            options={
                'verbose_name': 'bản ghi điểm danh',
                'verbose_name_plural': 'bản ghi điểm danh',
                'ordering': ['-date'],
                'unique_together': {('classroom', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='ngày kết thúc')),
                ('reason', models.TextField(verbose_name='lý do')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='trạng thái')),
                ('reviewer_comment', models.TextField(blank=True, null=True, verbose_name='nhận xét của người duyệt')),
                ('parent_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='liên hệ phụ huynh')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='leave_certificates/', verbose_name='giấy chứng nhận y tế')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cập nhật lần cuối')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='teachers.teacher', verbose_name='người duyệt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='students.student', verbose_name='học sinh')),
            ],
            options={
                'verbose_name': 'yêu cầu nghỉ phép',
                'verbose_name_plural': 'yêu cầu nghỉ phép',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng mặt'), ('excused', 'Có phép'), ('late', 'Đi muộn'), ('sick', 'Ốm')], default='present', max_length=20, verbose_name='trạng thái')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='lý do')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='học sinh')),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.attendancerecord', verbose_name='bản ghi điểm danh')),
            ],
            options={
                'verbose_name': 'điểm danh',
                'verbose_name_plural': 'điểm danh',
                'unique_together': {('attendance_record', 'student')},
            },
        ),
    ]
